In [74]:
# import
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [75]:
df=pd.read_csv('carprice.csv')
df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [76]:
df1=df[["carlength","carwidth","carheight","enginesize","stroke","horsepower","price"]]
df1

     carlength  carwidth  carheight  enginesize  stroke  horsepower    price
0        168.8      64.1       48.8         130    2.68         111  13495.0
1        168.8      64.1       48.8         130    2.68         111  16500.0
2        171.2      65.5       52.4         152    3.47         154  16500.0
3        176.6      66.2       54.3         109    3.40         102  13950.0
4        176.6      66.4       54.3         136    3.40         115  17450.0
..         ...       ...        ...         ...     ...         ...      ...
200      188.8      68.9       55.5         141    3.15         114  16845.0
201      188.8      68.8       55.5         141    3.15         160  19045.0
202      188.8      68.9       55.5         173    2.87         134  21485.0
203      188.8      68.9       55.5         145    3.40         106  22470.0
204      188.8      68.9       55.5         141    3.15         114  22625.0

[205 rows x 7 columns]

In [77]:
y=df1['price']
x=df1.drop('price',axis=1)

In [78]:
X_train, X_test, y_train, y_test = train_test_split(
     x, y, test_size=0.20)
from sklearn.linear_model import LinearRegression

model=LinearRegression()
model.fit(X_train.values,y_train)

LinearRegression()

In [79]:
prediction=regression.predict(X_test.values)
print(prediction)
print("\nscore is")
print(regression.score(X_test.values,y_test.values))

[12032.68581548  5592.18642277 12421.04841008 10953.27671037
  6797.18643846  7573.29877991 18123.03702979 17505.09673016
 34982.22521091 16767.46823428  7397.99023604  6853.26129593
  7746.03514102 11538.7830274  11942.47374993  6088.5468428
  7220.961068   11082.05023552  6902.04901843 22078.2892863
 12175.52613602  8896.86243298 10321.50100318 17645.29747811
 17079.53537062 15908.93018864 11365.91856703  6544.15965665
  6165.829064   10712.35247962  6470.32459721 11942.47374993
 14284.15667653  7746.03514102 11706.05345953  6165.829064
 22204.48655763 21414.19099676 10662.55594056  8669.2512033
 16286.46531038]

score is
0.7480421227775509

In [81]:
xtest = [190.9, 70.3, 54.9, 183, 3.64, 123]
xtest = np.array(xtest).reshape(1, -1)
print(regression.predict(xtest))

[22123.26078312]